services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5000:5000"
    environment:
      - BACKEND_BASE_URL=http://backend:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
